// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggvqxwbwxydiczjtpcyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdndnF4d2J3eHlkaWN6anRwY3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjM1ODcsImV4cCI6MjA2MDEzOTU4N30.RiePoVO7wvuHmce6bSVINKrIUGECn8-2ct5rBifT8-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);